### ISSUE TITLE
Faut-il supprimer l'extension as-ext-healthcareservice-authorization-number-arhgos?

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/IG-fhir-annuaire#100]
# Description du problème
En doublon avec HealthcareService.identifier ???

# Fichier•s concerné•s
as-healthcareservice-healthcare-activity

# Solution proposée
supprimer l'extension au profit de HealthcareService.identifier

**Comment by nriss** [comment]
Ok pour trouver un système permettant de discriminer
