### ISSUE TITLE
Création Exemples

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#110]
# Description du problème
Création exemple 1 médecin + 1 pharmacien avec leur structures associées

# Fichier•s concerné•s

# Solution proposée

**Comment by nriss** [comment]
Issue associée https://github.com/ansforge/IG-fhir-annuaire/issues/3

**Comment by nriss** [comment]
Je supprime l'issue car déjà ici : https://github.com/ansforge/IG-fhir-annuaire/issues/3
