### ISSUE TITLE
Lien situation exercice et exercice professionnel via PractiotionerRole

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-annuaire#114]
Bonjour, 

Si j'ai bien compris, l'exercice professionnel et la situation d'exercice sont tous les 2 représentés grâce à la ressource PractitionerRole. Cependant, je ne vois pas comment faire le lien entre 2 instances (une décrivant l'exercice professionnel et une décrivant la situation d'exercice) de cette ressource car il n'y a pas de champ qui permet de référencer un PractitionerRole dans la ressource PractitionerRole (à l'image de partOf pour organization par exemple). Est-ce une erreur de compréhension ?

**Comment by mchaabaoui** [comment]
Bonjour,

Contrairement à l'ancien modèle [simplifier](https://simplifier.net/packages/ANS.annuaire.fhir.r4), cette version du modèle **fusionne** en effet les deux notions MOS : **exerciceProfessionnel** et **situationExercice** en une seule notion : une instance de PractitionerRole contient à la fois la situation d'exercice et l'exercice professionnel.  

Dans ce contexte, la ressource PractitionerRole est définie comme une relation modélisation le rôle d'un PS dans une structure donnée pour un exercice pro donné. Il peut y avoir, pour un Practitioner à un instant donné,  autant d'instances PractitionerRole que de situations d'exercice et d'exercices professionnels.

**Comment by mchaabaoui** [comment]
<img width="443" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/70761903/3f84f0d5-8ce5-43db-947f-b53a1201338c">

**Comment by mchaabaoui** [comment]
<img width="431" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/70761903/828f9b72-2d81-45ba-8c08-c3052967dd04">

**Comment by sly-kereval** [comment]
Merci beaucoup pour ces informations.

Si j'ai bien compris, les informations de l'exercice professionnel et d'une situation d'exercice sont regroupées dans la même instance de PractitionerRole.

Par exemple, dans le cas d'un professionnel qui a un exercice professionnel et 2 situations d'exercice (par exemple libéral dans un cabinet et salarié dans un hôpital), il y a aura 2 instances de PractitionerRole : une contenant l'exercice professionnel et la première situation d'exercice, et une contenant de nouveau l'exercice professionnel et la seconde situation d'exercice. 

@mchaabaoui est-ce correct ?

**Comment by mchaabaoui** [comment]
oui, c'est exactement ça

**Comment by sly-kereval** [comment]
Merci !
