### ISSUE TITLE
Type d'identifiant d'un exemple de l'ancien service 

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-annuaire#117]
Bonjour, 

Dans un exemple d'instance d'Organization issu de l'ancien service, il y a 3 identifiers : 

```json
"identifier": [
        {
          "system": "urn:oid:1.2.250.1.71.4.2.2",
          "type": {
            "coding": [
              {
                "system": "http://www.interopsante.org/pam-fr/valuesets/identifier-type",
                "code": "IDNST"
              }
            ]
          },
          "use": "official",
          "value": "410005531586003"
        },
        {
          "system": "urn:oid:1.2.250.1.213.1.6.4.3",
          "type": {
            "coding": [
              {
                "system": "urn:oid:1.2.250.1.71.1.2.14",
                "code": "4"
              }
            ]
          },
          "use": "official",
          "value": "10005531586003"
        },
        {
          "system": "https://annuaire.sante.fr",
          "type": {
            "coding": [
              {
                "system": "http://www.interopsante.org/pam-fr/valuesets/identifier-type",
                "code": "INTRN"
              }
            ]
          },
          "use": "official",
          "value": "REJ10000000800887"
        }
      ]
```

Le type du deuxième identifier (code : 4, system : urn:oid:1.2.250.1.71.1.2.14) correspond d'après le DSFT "une identification RPPS rang", à quel type cela correspond-il dans le jdv [fr-organization-identifier-type](https://simplifier.net/packages/hl7.fhir.fr.core/1.1.0/files/783566) ? A quel slice du profil Organization cet identifiant correspond-il ?

**Comment by mchaabaoui** [comment]
voir PR [#120](https://github.com/ansforge/IG-fhir-annuaire/pull/120)

**Comment by nriss** [comment]
@sly-kereval peux-tu close cette issue si cette PR répond à ta question ?

**Comment by nriss** [comment]
Je viens de voir que FrOrganization.identifier.type est obligatoire, il faut donc fixer le type

Est-ce que EXTRN (identifiant externe) pourrait faire l'affaire @mchaabaoui ?
