### ISSUE TITLE
Location dans le profil PractitionerRole

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-annuaire#118]
Bonjour, 

Dans le profil PractitionerRole – organizationalrole de l'ancien service, il y avait un élément location. Dans le nouveau profil [AS PractitionerRole Profile](https://ansforge.github.io/IG-fhir-annuaire/ig/main/StructureDefinition-as-practitionerrole.html) il y a bien un élément location mais il est à 0..0 dans les profils correspondants DP et DR, est-ce normal ? Si oui, où sont mappées ces informations ?

**Comment by mchaabaoui** [comment]
Dans DR, la cardinalité devrait normalement être à 0..*.
ce sera corrigé
