### ISSUE TITLE
Cardinalité slice Practitioner.qualification.code

### ISSUE THREAD

**Issue by sly-kereval** [ansforge/IG-fhir-annuaire#119]
Bonjour, 

Dans le profil Practitioner, nous nous interrogeons sur la cardinalité des slices de qualification.code.coding. Est-ce normal que chaque slice ait une cardinalité 0..* et que l'élément coding ait une cardinalité 0..* ? 
Dans notre compréhension, chaque slice aurait une cardinalité 0..1 et l'élément coding aurait une cardinalité maximale de 2 pour pouvoir renseigner un diplôme et son type (degreeType).

**Comment by mchaabaoui** [comment]
Je partage entièrement la remarque.

**Comment by nriss** [comment]
C'est plutôt qualification qui devrait être slicée plutôt que coding, c'est ça ?
Le problème vient de FrPractitioner plutôt ?

**Comment by nriss** [comment]
@mchaabaoui est-on sûr qu'il n'y a qu'un degree, profession, savoirFaire par personne ?

J'ai envie de laisser tel quelle : 
- il peut y avoir plusieurs de chacune des slices pour chaque PS (Practitioner.qualification:slice)
- il ne sert à rien de limiter la cardinalité du nombre de coding, on peut laisser libre choix à l'utilisateur de mettre des synonymes (Practitioner.qualification:slice.code.coding)

Il y a potentiellement besoin de contraindre davantage au niveau des profils applicatifs ? Mais pour cela il me faut un expert métier qui me confirme ça

**Comment by flachalESEA** [comment]
@nriss 

Je te propose de poser la question aux équipes terrain. Les GRADeS sont là pour ça. 

A première vue je dirais qu'il peut y avoir plusieurs vies chez un professionnel et également qu'il n'est pas rare de rencontrer des Médecins disposants de plusieurs CAPA par exemple.

**Comment by nriss** [comment]
@flachalESEA tu es donc d'accord avec ma proposition ?

**Comment by flachalESEA** [comment]
Oui, ça va bien !
