### ISSUE TITLE
PractitionerRole - slice specialty

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#137]
# Description du problème
Les slices de l'attribut specialty ne reprennent pas le type [AsCodeableConceptTimedProfile](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-codeableconcept-timed.html) de l'attribut profilé. 
Ne devraient - ils pas eux aussi avoir ce type ? 

![image](https://github.com/ansforge/IG-fhir-annuaire/assets/122790741/5bea7cd5-aa88-4be2-b1fe-bf38a876d830)

# Fichier•s concerné•s
[PractitionerRole](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-practitionerrole.html)

# Solution proposée

**Comment by nriss** [comment]
Il est vrai que c'est étrange! Je clos l'issue car elle n'est plus d'actualité en 1.0.0-ballot-3
