### ISSUE TITLE
[NOS] Créer la ConceptMap de correspondance NOS / Practitioner.gender

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#152]
# Description du problème

- Créer la ConceptMap dans le NOS
- Renseigner la possiblité d'usage de cette CM dans le narratif

# Fichier•s concerné•s

- Profil Practitioner

**Comment by nriss** [comment]
Est-ce que l'on peut clore ce point @paulineheurtebise ? Les travaux ont été lancés côté MOS ?

**Comment by paulineheurtebise** [comment]
J'ai envoyé la DM en décembre/janvier, pas eu de retour coté NOS encore.

**Comment by nriss** [comment]
https://mos.esante.gouv.fr/NOS/ASS_A33-AdministrativeGender-Sexe/ASS_A33-AdministrativeGender-Sexe.pdf
