### ISSUE TITLE
[IG-0.1.0]  Mise à jour de la page d'accueil - current version which supersedes this version

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/IG-fhir-annuaire#155]
Sur la page d'accueil de l'IG [0.1.0](https://interop.esante.gouv.fr/ig/fhir/annuaire/0.1.0/), merci de mettre à jour la version courante de l'IG
<img width="910" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/70761903/f114f064-a7fc-445d-9e3c-76300437163d">

# Solution proposée
1.0.0-ballot-3 au lieu de 1.0.0-ballot-2

**Comment by nriss** [comment]
Fait, le serveur sera mis à jour demain :)
https://github.com/ansforge/IG-website-release/commit/83f5b3952bc0049af26f12f65215dc8cebb8da0c

Merci pour avoir identifié l'erreur
