### ISSUE TITLE
Mise à jour des liens pointant vers les issues

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/IG-fhir-annuaire#156]
# Description du problème
Sur la page https://interop.esante.gouv.fr/ig/fhir/annuaire/, lorsque l'on clique sur les liens "Issue sur l'API" ou "Issue sur l'IG" , Github demande un mot de passe.

# Fichier•s concerné•s
https://interop.esante.gouv.fr/ig/fhir/annuaire/
<img width="214" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/70761903/37914d35-ea74-4443-b589-bd72d56d5111">

# Solution proposée

- Remplacer le lien https://github.com/ansforge/annuaire-sante-fhir-serveur/issues/new par https://github.com/ansforge/annuaire-sante-fhir-serveur/issues
- remplacer le lien https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/new par https://github.com/ansforge/annuaire-sante-fhir-documentation/issues

**Comment by nriss** [comment]
Corrigé en même temps que https://github.com/ansforge/IG-fhir-annuaire/issues/155
