### ISSUE TITLE
Extension définie pour le mauvais profil : AS Smart Card Extension 

### ISSUE THREAD

**Issue by flachalESEA** [ansforge/IG-fhir-annuaire#158]
# Description du problème
L'extension AS Smart Card Extension est définie pour le profil "Practitioner" hors elle est présente dans la ressource "PractitionerRole"

indiqué notamment ici pour les search parameters dans PractitionerRole: https://ansforge.github.io/annuaire-sante-fhir-documentation/pages/documentation/resources/practitioner-role.html#35-header 
Hors l'extension est définie pour le profil Practitioner: https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-dp-practitioner.html

Une recherche dans l'AS renvoie bien les extensions number/type-smartcard dans le profil PractitionerRole

# Fichier•s concerné•s
Ca dépends de si c'est la définition de l'extension ou celles des profils qui ne sont pas bonnes. L'extension est définie ici:
https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-ext-smartcard.html

# Solution proposée
La logique voudrait que l'extension soit plutôt du côté du RPPS (donc de Practitioner)

**Comment by flachalESEA** [comment]
Nevermind, j'ai compris, l'IG en trial a changé la localisation de cette extension tandis que l'API est encore sur des specs 0.1.0 de l'IG. 

Pour le coup je suis plutôt ok avec le déménagement de cette extension.

**Comment by flachalESEA** [comment]
Peut-être en warning sur la page d'accueil du trial, mettre les grands changements.

**Comment by nriss** [comment]
> Peut-être en warning sur la page d'accueil du trial, mettre les grands changements.

Mettre un lien vers l'historique, préciser que les extensions ont également été déplacées.
![image](https://github.com/ansforge/IG-fhir-annuaire/assets/48218773/9ca5f1dd-c3bf-4673-b7ab-9637dd527b5b)

**Comment by nriss** [comment]
Je clos l'issue, sera traité avec https://github.com/ansforge/IG-fhir-annuaire/issues/159
