### ISSUE TITLE
Identifiers AS Organization : CodeSystem fr-v2-0203 

### ISSUE THREAD

**Issue by GCHASTIN** [ansforge/IG-fhir-annuaire#161]
# Description du problème
Dans le profil AS Organization, c'est le lien simplifier qui est indiqué pour le CodeSystem fr-v2-0203 pour les slices idNatSt, finess, adeliRang, rppsRang : http://interopsante.org/CodeSystem/fr-v2-0203
Ne devrait on pas y indiquer celui-ci : https://hl7.fr/ig/fhir/core/CodeSystem/fr-core-v2-0203 pour être en adéquation avec l'IG Fr Core ?

# Fichier•s concerné•s
AS Organization Profile

# Solution proposée
Remplacer http://interopsante.org/CodeSystem/fr-v2-0203 par https://hl7.fr/ig/fhir/core/CodeSystem/fr-core-v2-0203

**Comment by nriss** [comment]
Hello, 
Je suis d'accord avec toi! Cependant, l'IG FrCore n'est pas encore publié.
Le package n'étant pas encore dans le FHIR Package Registry (https://registry.fhir.org/), il n'est pas encore possible d'hériter des futurs profils FrCore.
