### ISSUE TITLE
[AS Organization Profile] Organization. type[typeEtablissement] : absence de binding, pas de discrimination

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#162]
# Description du problème

Cf https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/158#event-11595819752

<img width="1047" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/48218773/757cbd9f-f3ce-4701-ac7b-37c6b192a828">

Cette attribut n'a pas de binding.

* type[typeEtablissement] ^short = "Le type d’établissement détermine si c'est un établissement principal ou secondaire."

**Comment by GCHASTIN** [comment]
Seul élément slicé de l'élément type n'étant pas rattaché à une terminologie spécifique.
Ce type a t'il réellement un sens du point de vue métier?
La slice rule étant open (si je ne me trompe pas) ne peut on pas s'en passer?

**Comment by nriss** [comment]
Je suis d’accord avec toi @GCHASTIN

**Comment by nriss** [comment]
Type d'établissement est un texte dans le MOS 
<img width="717" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/48218773/c9bf4621-2e24-4346-b727-cdcc8167749a">

organizationType vient de FrCore

**Comment by nriss** [comment]
Solution envisagée : créer une extension code avec une fixed value.
