### ISSUE TITLE
Associer l'extension iso21090-ADXP-streetNameType et la TRE_R35-TypeVoie

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#185]
# Description du problème

L'extension est un string : http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameType

En France, le type de voie est fixée par la TRE R35 : https://mos.esante.gouv.fr/NOS/TRE_R35-TypeVoie/TRE_R35-TypeVoie.pdf

<img width="720" alt="image" src="https://github.com/ansforge/IG-fhir-annuaire/assets/48218773/f1f169d5-9e2b-4ee5-bd23-69cd11ac910c">

Au préalable, il faudra vérifier que le mapping TypeVoie est bien associé à l'extension http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameType, @mchaabaoui peux-tu me confirmer ça ?

Merci d'avance! 
JDV associé : https://mos.esante.gouv.fr/NOS/JDV_J103-TypeVoie-RASS/JDV_J103-TypeVoie-RASS.pdf

Issue associée : https://github.com/ansforge/annuaire-sante-fhir-serveur/issues/42

**Comment by mchaabaoui** [comment]
oui, le mapping TypeVoie est bien associé à l'extension.
voici un exemple : 
```json
  "line": [
          null
        ],
        "_line": [
          {
            "extension": [
              {
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber",
                "valueString": "19"
              },
              {
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-buildingNumberSuffix",
                "valueString": "Bis"
              },
              {
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameType",
                "valueString": "R"
              },
              {
                "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetNameBase",
                "valueString": "JOUFFROY ABBANS"
              }
            ]
          }
        ],
        "city": "75017 PARIS 17E  ARRONDISSEMENT",
        "postalCode": "75017"
      }
    ],
```

**Comment by nriss** [comment]
Est-ce conforme au JDV J103 ou bien à la norme NF Z10-011? 
https://www.boutique.afnor.org/fr-fr/norme/nf-z10011/adresse-postale-redaction-de-ladresse-postale-regles-de-presentation-du-cou/fa178533/40541

**Comment by mchaabaoui** [comment]
conforme plutôt au DV J103

**Comment by nriss** [comment]
Je clos car le binding était déjà fait finalement : 
![image](https://github.com/ansforge/IG-fhir-annuaire/assets/48218773/21525dad-4299-4014-a397-5ac8914fb80e)
