### ISSUE TITLE
Certains attributs non pris en compte lors d'un GET sur le paramètre _elements

### ISSUE THREAD

**Issue by BenkhoEsea** [ansforge/IG-fhir-annuaire#234]
Bonjour,

Je me présente, je suis le nouveau CP Intérop arrivé depuis 2 semaines chez ESEA Nouvelle Aquitaine. Pour me familiariser avec le FHIR et L'API , je faisais des requêtes GET sur POSTMAN sur l'annuaire de santé.
En voulant afficher seulement certaines données, j'ai utilisé le paramètre _elements : par exemple : 

**GET {{api_url}}/Organization?_elements=address,name,identifier** 

Seuls name et identifier remonte, je ne sais pas pourquoi. On m'a conseillé de faire une issue auprès de vous. 

Voici un échantillon du code réponse : 

{
    "resourceType": "Bundle",
    "id": "c82a8a49-5e4c-4a84-a17c-b5734d604a46",
    "meta": {
        "lastUpdated": "2024-09-16T10:14:27.034+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://gateway.api.esante.gouv.fr/fhir/v1/Organization?_elements=address%2Cname%2Cidentifier"
        },
        {
            "relation": "next",
            "url": "https://gateway.api.esante.gouv.fr/fhir/v1?_getpages=c82a8a49-5e4c-4a84-a17c-b5734d604a46&_pageId=660eb2b87bf92f0e6c8a2857_uSL3B7TBTiho6-FtqVBFvXV1PcZOUNAat2bQnier4sTx1rl_U-4d5IlkcwOuEowW0gjXvNnUTyZgRdYddaNzj-AVN3kQ25hnb3p6WZwR-hYM8IeU_XxusVd376q61mf5sszhbPjQjj5dxEnwhYy7MhWD0XapIyM_CLk7SDk_qZrbXleVIr3zBszfxV479tyJWSnO4QA%3D%3D&_bundletype=searchset&_elements=address,identifier,name"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://gateway.api.esante.gouv.fr/fhir/v1/Organization/001-02-1089936",
            "resource": {
                "resourceType": "Organization",
                "id": "001-02-1089936",
                "meta": {
                    "extension": [
                        {
                            "url": "https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition/as-data-trace",
                            "extension": [
                                {
                                    "url": "data-registration-authority",
                                    "valueCodeableConcept": {
                                        "coding": [
                                            {
                                                "system": "1.2.250.1.213.1.6.1.57",
                                                "code": "RPPS"
                                            }
                                        ]
                                    }
                                },
                                {
                                    "url": "data-information-system",
                                    "valueCode": "RPPS"
                                }
                            ]
                        }
                    ],
                    "versionId": "1",
                    "lastUpdated": "2024-04-04T14:01:28.370+00:00",
                    "source": "https://annuaire.sante.fr",
                    "profile": [
                        "http://interop.esante.gouv.fr/ig/fhir/annuaire-donnee-publique/StructureDefinition/as-organization"
                    ],
                    "tag": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
                            "code": "SUBSETTED",
                            "display": "Resource encoded in summary mode"
                        }
                    ]
                },
                "identifier": [
                    {
                        "use": "official",
                        "type": {
                            "coding": [
                                {
                                    "system": "http://interopsante.org/CodeSystem/fr-v2-0203",
                                    "code": "IDNST"
                                }
                            ]
                        },
                        "system": "urn:oid:1.2.250.1.71.4.2.2",
                        "value": "2981834922"
                    },
                    {
                        "use": "official",
                        "type": {
                            "coding": [
                                {
                                    "system": "http://interopsante.org/CodeSystem/fr-v2-0203",
                                    "code": "SIREN"
                                }
                            ]
                        },
                        "system": "http://sirene.fr",
                        "value": "981834922"
                    }
                ],
                "name": "SELARL CABINET CHB"
            }
        },

Je vous remercie d'avance pour votre aide.

Cordialement,

**Comment by zilliw** [comment]
Bonjour @BenkhoEsea,

Suite à votre analyse, vous constatez que le paramètre _elements n'affiche pas le champ address. Cette information n'est pas remontée car l'identifiant 981834922 (identifiant SIREN) renvoie une entité juridique ( qui ne dispose d'aucune information sur l'adresse juridique.

Bien Cordialement,

**Comment by BenkhoEsea** [comment]
Bonjour @zilliw , 

Merci pour ta réponse, je comprends pour mon premier exemple, mais par contre j'ai un deuxième exemple : 

**GET {{api_url}}/PractitionerRole?_elements=given,family**

Je n'ai pas les prénoms et nom de familles qui remontent. N'ai je pas compris quelque chose ?

Voici un extrait de la réponse : 
{
    "resourceType": "Bundle",
    "id": "9c601863-0cd1-46bf-af8d-a91bc2b4a4e7",
    "meta": {
        "lastUpdated": "2024-09-23T12:24:12.211+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "self",
            "url": "https://gateway.api.esante.gouv.fr/fhir/v1/PractitionerRole?_elements=given%2Cfamily"
        },
        {
            "relation": "next",
            "url": "https://gateway.api.esante.gouv.fr/fhir/v1?_getpages=9c601863-0cd1-46bf-af8d-a91bc2b4a4e7&_pageId=660eb2ba7bf92f0e6c8a35ce_usLQrXHh8sUk-NpMBSb1A0jbOVIw7umncCW-QTWrAI9fNWq25r4euZMcUtXyJB_89r4V7qNFY_AQydDdt4Cq0eHTk6GVqI_dVoG8jQuU5AjFmTG04UaC24CxUj5i4c1uQ0EqeaejSC4yTNQr93dDm8zFMiXSgFVVsOn5cLsqJaXWE0q4TD4qyEaRNrD12C1OlseGTkhXob3LM0TJw&_bundletype=searchset&_elements=family,given"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://gateway.api.esante.gouv.fr/fhir/v1/PractitionerRole/005-3622192-6726113",
            "resource": {
                "resourceType": "PractitionerRole",
                "id": "005-3622192-6726113",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2024-04-04T14:01:30.444+00:00",
                    "source": "https://annuaire.sante.fr",
                    "profile": [
                        "http://interop.esante.gouv.fr/ig/fhir/annuaire-donnee-publique/StructureDefinition/as-practitionerrole"
                    ],
                    "tag": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
                            "code": "SUBSETTED",
                            "display": "Resource encoded in summary mode"
                        }
                    ]
                }
            }
        },
        {
            "fullUrl": "https://gateway.api.esante.gouv.fr/fhir/v1/PractitionerRole/005-381264-7436305",
            "resource": {
                "resourceType": "PractitionerRole",
                "id": "005-381264-7436305",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2024-04-04T14:01:30.471+00:00",
                    "source": "https://annuaire.sante.fr",
                    "profile": [
                        "http://interop.esante.gouv.fr/ig/fhir/annuaire-donnee-publique/StructureDefinition/as-practitionerrole"
                    ],
                    "tag": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
                            "code": "SUBSETTED",
                            "display": "Resource encoded in summary mode"
                        }
                    ]
                }
            }
        },
        {

Merci d'avance de votre réponse,
Cordialement

**Comment by zilliw** [comment]
Bonjour @BenkhoEsea,

En effet, après vérification avec l'équipe, le paramètre _element n'a pas été repris sur l'ensemble des ressources. 

Nous travaillons actuellement sur une nouvelle version de l'API qui devrait prochainement sortir. Le paramètre _element ne sera pas repris (pour le moment) mais nous l'implémenterons dans un second temps.

Désolé pour la gêne occasionnée.

**Comment by BenkhoEsea** [comment]
Merci pour les informations ! 

Pas de soucis, je découvre le FHIR.
