### ISSUE TITLE
Code postal dans le champ City (address de Organization)

### ISSUE THREAD

**Issue by flrt** [ansforge/IG-fhir-annuaire#31]
# Description du problème
Dans le champ `city`, le code postal est présent :

```
"city": "97410 ST PIERRE"
"city": "35000 RENNES"

```

# Fichier•s concerné•s
Ressource Organization

# Solution proposée
Ne pas avoir le code postal dans le champ `city`. Il doit être présent dans `postalCode`

**Comment by mchaabaoui** [comment]
le problème est déjà connu : 
https://github.com/ansforge/annuaire-sante-fhir-documentation/issues/26

**Comment by nriss** [comment]
Je clos l'issue qui n'est pas dans le bon repo et qui est en doublon
