### ISSUE TITLE
Résolution des URL de Code System

### ISSUE THREAD

**Issue by flrt** [ansforge/IG-fhir-annuaire#32]
# Description du problème
Les URL de Code System ne sont pas résolvables

```
"valueCodeableConcept": {
            "coding": [
              {
                "system": "https://mos.esante.gouv.fr/NOS/TRE_R257-TypeBAL/FHIR/TRE-R257-TypeBAL",
                "code": "APP"
              }
            ]
          }
```

Ex : 
[https://mos.esante.gouv.fr/NOS/TRE_R257-TypeBAL/FHIR/TRE-R257-TypeBAL](https://mos.esante.gouv.fr/NOS/TRE_R257-TypeBAL/FHIR/TRE-R257-TypeBAL)
Ne renvoie pas de ressource.

# Fichier•s concerné•s

# Solution proposée
L'accessibilité des CS. Chaque ressource résolvable en suivant son URL.

**Comment by nriss** [comment]
Nous avons identifié ce problème, des travaux sont en cours pour incorporer le NOS dans le SMT.
