### ISSUE TITLE
complétude des données Finess pour les équipement sociaux

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/IG-fhir-annuaire#41]
# Description du problème
compléter les données manquantes sur les les équipements sociaux

# Fichier•s concerné•s
le profil générique "https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition/as-healthcareservice-social-equipment",
ainsi que les profils applicatifs "dp" et "dr"

# Solution proposée
ajouter les données suivantes : 
•	agregatDisciplineEquipementSocialeNiv1 : (TRE_R298-AgregatDisciplineEquipSocNiv1)
•	agregatDisciplineEquipementSocialeNiv2 : (TRE_R299-AgregatDisciplineEquipSocNiv2)
•	agregatDisciplineEquipementSocialeNiv3 : (TRE_R300-AgregatDisciplineEquipSocNiv3)
•	agregatClienteleNiv2 : (TRE_R293-AgregatClienteleNiv2)
•	agregatClienteleNiv3 : (TRE_R294-AgregatClienteleNiv3)
•	capaciteAutorisee
•	capaciteAutoriseeFemme 
•	capaciteAutoriseeHomme 
•	capaciteAutoriseeHabiliteeAideSociale 
•	ageMinAutorise 
•	ageMaxAutorise 
•	suppressionAutorisation 
•	capaciteInstallee 
•	capaciteInstalleeFemme 
•	capaciteInstalleeHomme 
•	capaciteInstalleeHabiliteeAideSociale 
•	ageMinInstalle 
•	ageMaxInstalle 
•	suppressionInstallation 
•	sourceInformationInstallation  (TRE_R301-SourceInformationInstallation

**Comment by mchaabaoui** [comment]
Pour partage, 1ère synthèse de l'étude réalisée autour du Mapping FHIR données FINESS.

DisciplineSociale - AS HealthcareService Social Equipment Profile
 
5 données dont les nomenclatures sont transmises par FINESS mais sont utilisées à des fins statistiques -> non repris par l'Annuaire : 
•	agregatDisciplineEquipementNiv1 + agregatDisciplineEquipementNiv2 + agregatDisciplineEquipementNiv3
•	agregatClienteleNiv2 + agregatClienteleNiv3
 
17 données est à ajouter  (source données FINESS) : 
•	dateMajAutorisation  -> Extension à créer 
•	dateDernièreInstallation  -> Extension à créer 
•	capaciteAutorisee + capaciteAutoriseeFemme + capaciteAutoriseeHomme + capaciteAutoriseeHabiliteAidesociale -> Extension à créer
•	capaciteInstallee + capaciteInstalleeFemme + capaciteInstalleeHomme + capaciteInstalleeHabiliteAidesociale -> Extension à créer 
•	ageMinAutorisee + ageMaxAutorisee  -> Extension à créer 
•	ageMinInstallee + ageMaxInstallee  -> Extension à créer 
•	suppressionAutorisation -> Extension à créer 
•	suppressionInstallation -> Extension à créer 
•	sourceInformationInstallation -> Extension à créer

**Comment by paulineheurtebise** [comment]
• capaciteAutorisee + capaciteAutoriseeFemme + capaciteAutoriseeHomme + capaciteAutoriseeHabiliteAidesociale 
• capaciteInstallee + capaciteInstalleeFemme + capaciteInstalleeHomme + capaciteInstalleeHabiliteAidesociale
-> dans le ROR il y aune extension [capacite ](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/extensions/RORLocationSupportedCapacity.fsh) qui s'applique à Location et qui propose un type de capacite et un nombre donc dans notre cas si on applique cette logique, la donnée serai divisée en 2.
J'ai pas trouvé d'extension publiée sur la capacité

• ageMinInstallee + ageMaxInstallee -> Se baser sur Extension ROR [RORHealthcareServicePatientType](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/extensions/RORHealthcareServicePatientType.fsh)
• ageMinAutorisee + ageMaxAutorisee -> Idem

• suppressionAutorisation -> Extension à créer, pas trouvé d'équivalent ROR ou publiée
• suppressionInstallation -> Extension à créer, pas trouvé d'équivalent ROR ou publiée
• sourceInformationInstallation -> Extension à créer, pas trouvé d'équivalent ROR ou publiée
• dateMajAutorisation -> Extension à créer, pas trouvé d'équivalent ROR ou publiée
• dateDernièreInstallation -> Extension à créer, pas trouvé d'équivalent ROR ou publiée

**Comment by mchaabaoui** [comment]
• suppressionAutorisation -> Extension déjà  publiée : as-ext-healthcareservice-delete-autorization-implantation

**Comment by mchaabaoui** [comment]
je propose la création d'une extension "as-ext-healthcareservice-supported-capacity" qui regroupera  : capaciteAutorisee + capaciteAutoriseeFemme + capaciteAutoriseeHomme + capaciteAutoriseeHabiliteAidesociale + capaciteInstallee + capaciteInstalleeFemme + capaciteInstalleeHomme + capaciteInstalleeHabiliteAidesociale

**Comment by mchaabaoui** [comment]
idem une extension "as-ext-healthcareservice-patient-type" regroupant : ageMinInstallee + ageMaxInstallee + ageMinAutorisee + ageMaxAutorisee + [supportedPatientInfo](https://mos.esante.gouv.fr/NOS/JDV_J137-Clientele-RASS/FHIR/JDV-J137-Clientele-RASS/JDV_J137-Clientele-RASS-FHIR.json)

**Comment by nriss** [comment]
Ca ressemble à ce qui est fait dans le ror : https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-healthcareservice.html patient-type

**Comment by mchaabaoui** [comment]
une seule extension "as-ext-healthcareservice-authorization" (au lieu de 3 actuellement) qui regroupera : dateAutorisation, dateMajAutorisation et suppressionAutorisation,

**Comment by mchaabaoui** [comment]
idem une extension "as-ext-healthcareservice-implantation" qui accueillera dateDerniereInstallation,  suppressionInstallation et sourceInformationInstallation

**Comment by mchaabaoui** [comment]
Finalement, on a créé une seule extension appelée as-ext-healthcareservice-authorization regroupant tous ces champs  :  

- dateAuthorization 0..1 and 			// dateDecision
- periodAuthorization 0..1 and 		// datePremiereMEO +  dateFin 
- dateUpdateAuthorization 0..1 and 	//dateMajAutorisation
- deleteAuthorization 0..1 and 		//suppressionAutorisation
- dateLastInstallation 0..1 and 		// dateDerniereInstallation
- deleteInstallation 0..1 and 		// suppressionImplantation ou suppressionInstallation
- sourceReportInstallation 0..1 		// sourceInformationInstallation
