### ISSUE TITLE
complétude des données Finess pour les structures

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/IG-fhir-annuaire#42]
# Description du problème
compléter les données manquantes sur les structures

# Fichier•s concerné•s
le profil générique "https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition/as-organization"
et les profils applicatifs "dp" et "dr"

# Solution proposée
ajout des données suivantes : 
•	agregatStatutJuridiqueNiv1 : (TRE_R68-FinessAgregatStatutJuridiqueNiv1)
•	agregatStatutJuridiqueNiv2 : (TRE_R69-FinessAgregatStatutJuridiqueNiv2
•	champActivite (TRE_R227-ChampActivite)
•	typeEtablissement
•	agregatCategorieEtablissementNiv1 (TRE_R63-AgregatCategorieEtablissementNiv1)
•	agregatCategorieEtablissementNiv2  (TRE_R65-AgregatCategorieEtablissement)
•	agregatCategorieEtablissementNiv3 (TRE_R65-AgregatCategorieEtablissement)
•	numeroEducationNationale 
•	denominationEG 
•	numéroFinessetablissementPrincipal 
•	modeFixationTarif (TRE_R74-ModeFixationTarifaire)
•	natureEtablissement 
•	aideFinanciere (TRE_R241-TypeAideFinanciere)
•	habilitationSoinSansConsentement
•	hebergementFamille 
•	dateCaducite 
•	constatCaducite 
•	typeFermeture  (TRE_R286-TypeFermeture)
•	dateAutorisation 
•	accessibiliteLieu (TRE_R202-AccessibiliteLieu)
•	zonePoser 
•	niveauRecoursORSAN (TRE_R284-NiveauRecoursORSAN)
•	venteLigneURL 
•	nbPlaceAideSocialeTemporaire 
•	nbPlaceAideSocialePermanent 
•	capaciteAccueil
•	capaciteHabitation 
•	tarif 
•	lieuEG 
•	dateModificationSIRET 
•	origineModificationSIRET 
•	dateModificationSIREN
•	origineModificationSIREN

**Comment by mchaabaoui** [comment]
Pour partage, 1ère synthèse de l'étude réalisée autour du Mapping FHIR données FINESS.

EntiteJuridique - Organization
2 données ont pour source FINESS mais sont considérées comme technique et obsolètes : 
•	dateModificationSiren 
•	origineModificationSiren
 
3 données dont les nomenclatures sont transmises par FINESS mais sont utilisées à des fins statistiques -> non repris par l'Annuaire : 
•	agregatStatutJuridiqueNiv1
•	agregatStatutJuridiqueNiv2
•	agregatStatutJuridiqueNiv3
 
1 donnée est à ajouter (source données FINESS) : 
•	typeFermeture -> Extension à créer à l'image de celle qui est existante dans le ROR actuellement. Le ROR héritera à l'avenir de l'extension de l'Annuaire. 
 
 
EntiteGeographique - Organization
2 données ont pour source FINESS mais sont considérées comme technique et obsolètes : 
•	dateModificationSIRET
•	origineModificationSIRET
 
3 données dont les nomenclatures sont transmises par FINESS mais sont utilisées à des fins statistiques -> non repris par l'Annuaire : 
•	agregatCategorieEtablissementNiv1
•	agregatCategorieEtablissementNiv2
•	agregatCategorieEtablissementNiv3
 
 6 données est à ajouter  (source données FINESS) : 
•	typeFermeture -> Extension à créer à l'image de celle qui est existante dans le ROR actuellement. Le ROR héritera à l'avenir de l'extension de l'Annuaire. 
•	modeFixationTarifaire -> Extension à créer
•	natureEtablissement -> Extension à créer 
•	typeEtablissement -> slice sur le type à créer (discriminateur =id)
•	dateCaducite et constatCaducite -> Extension à créer

**Comment by paulineheurtebise** [comment]
Pour le typeFermeture l'extension ROR aujourd'hui est : https://interop.esante.gouv.fr/ig/fhir/ror/StructureDefinition-ror-organization-closing-type.html

**Comment by mchaabaoui** [comment]
@paulineheurtebise 
Question : ces données (à ajouter) sont-elles toutes publiques?

**Comment by paulineheurtebise** [comment]
Ah mince je ne sais pas du tout, qui détermine cette information, est ce que c'est FINESS ?

**Comment by paulineheurtebise** [comment]
De notre discussion de jeudi dernier (12/10) avec Alexis, par défaut les données FINESS sont publiques. 

Sur les extensions à créer : 
- typeFermeture --> Extension ROR [ROROrganizationClosing](https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/input/fsh/extensions/ROROrganizationClosingType.fsh)
- modeFixationTarifaire --> Pas d'extension ROR ni d'extension publiée qui convienne
- natureEtablissement -->  Pas d'extension ROR ni d'extension publiée qui convienne
- dateCaducite et constatCaducite --> Pas d'extension ROR, se baser sur [organization-period](http://hl7.org/fhir/extensions/StructureDefinition-organization-period.html) ?

**Comment by mchaabaoui** [comment]
ont été créées les extensions suivantes  :  
typeFermeture --> as-ext-organization-closing-type
modeFixationTarifaire --> as-ext-organization-pricing-model
natureEtablissement --> as-ext-organization-budget-type
dateCaducite et constatCaducite --> as-ext-organization-authorization-deadline
