### ISSUE TITLE
Identifiant local des practitioner - risque d'ambiguité

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#58]
L'identifiant local à portée nationale peut engendrer des collisions:
Celui-ci peut être : Id Cabinet ADELI/N° de registre, FINESS/N° de registre, SIREN/N° de registre, SIRET/N° de registre ou Id Cabinet RPPS/N° de registre

Or le SIREN et FINESS font tous les deux 9 caractères, il y a un risque d'ambiguïté. 

Il faut donc préciser le système à utiliser (par ex : idnat ps)

Ambiguité remontée par @Monstermanu

**Comment by nriss** [comment]
Deux possibilités, il faudrait mieux le faire avec un URL : 

System: 
* finess : [finess.local.esante.gouv.fr](http://finess.local.esante.gouv.fr/)
* siren: [siren.local.esante.gouv.fr](http://siren.local.esante.gouv.fr/)
* siret : [siret.local.esante.gouv.fr](http://siret.local.esante.gouv.fr/)
* rpss : [rpss.local.esante.gouv.fr](http://rpss.local.esante.gouv.fr/)
Avec dans la value : xxxxx/12345 ou xxxxx est lidentifiant finess/siren/siret ou rpss


System : 
* finess : [finess.local.esante.gouv.fr/xxxxx](http://finess.local.esante.gouv.fr/xxxxx)
* siren: [siren.local.esante.gouv.fr](http://siren.local.esante.gouv.fr/xxxxx)[/xxxxx](http://siren.local.esante.gouv.fr/xxxxx)
* siret : [siret.local.esante.gouv.fr](http://siret.local.esante.gouv.fr/xxxxx)[/xxxxx](http://siret.local.esante.gouv.fr/xxxxx)
* rpss : [rpss.local.esante.gouv.fr](http://rpss.local.esante.gouv.fr/xxxxx)[/xxxxx](http://rpss.local.esante.gouv.fr/xxxxx)
           Avec dans la value :12345 ou xxxxx est lidentifiant finess/siren/siret ou rpss

**Comment by abreithoff** [comment]
@Monstermanu quel intéret reste-t-il a maintenir le type d'identifiant avec cette solution ?

**Comment by Monstermanu** [comment]
> @Monstermanu quel intéret reste-t-il a maintenir le type d'identifiant avec cette solution ?

Effectivement l'information que l'identifient est local est porté par le system. Le seul intérêt que je vois serait si on veut trouver des identifiants locaux ou exclure des identifiants locaux dans les résultats de recherche sans avoir à exclure une liste de system ou à parser les systems pour voir s'il y a local dedans ou les identifiants pour voir s'il y a un / dedans. Mais je ne suis pas sûr que ce soit un besoin fréquent (j'aurais même tendance à dire que ça ne devrait pas être le cas, mais je ne connais pas tous les usages donc je préfère rester prudent).

**Comment by nriss** [comment]
Pour ma part, j'ai trouvé important de modéliser les identifiants RPPS et ADELI directement (sans passer par l'IDNATPS).

Dans mon ancienne vie en startup, je n'avais aucune idée de comment fonctionner l'idnatps qui est assez complexe, mais les numéros RPPS et ADELI étant facile à utiliser/comprendre, je trouve ça précieux pour l'écosystème que ce practitioner permette la modélisation d'ADELI et RPPS sans passer par l'IDnatPS.

Pour l'identifiant local, j'en suis moins persuadé en effet.

Je peux également commenter ces slices (et les décommenter si le besoin émerge), et laisser juste RPPS et ADELI

**Comment by Monstermanu** [comment]
Je suis d'accord que la notion d'IdNatPS est compliquée et qu'il vaut mieux passer par les identifiants "purs" quand on peut.
Néanmoins elle est encore utilisée au moins pour la CPS (sauf à ce que ça ait évolué dernièrement, c'est la chaîne de caractère de l'IdNatPS qui est indiqué dans le certificat dans les cartes) et pour le DMP (il a justement été choisi lors de l'élaboration des spec du DMP d'utiliser l'IdNatPS pour que l'identifiant soit directement récupérable dans les cartes CPS - l'usage nominal à ce moment là était l'authentification directe à partir d'une CPS - et que les acteurs n'aient pas à se préoccuper de modifier cette chaine de caractère pour la connexion au DMP). Du coup j'aurais quand même tendance à recommander d'avoir les deux dans l'annuaire pour éviter des manipulations côté SI utilisateur.

**Comment by abreithoff** [comment]
D'accord avec toi @Monstermanu . Même si la lecture de l'identifiant directement dans la carte n'est plus la cible, c'est encore très utilisé. Ce sera l'occasion pour moi d'échanger avec les équipes CPS sur l'avancement de la cible...
Autre remarque @nriss à laquelle je pense suite à la lecture du premier commentaire de @Monstermanu, je pense que, dans ta proposition, on mélange deux notions : 

> l'identifiant FINESS ET, FINESS EJ, SIREN, SIRET et RPPS_RANG 

> La source FINESS, SIREN et RPPS

A voir ce qu'on veut exprimer au niveau du system mais pour moi, c'est soit l'un soit l'autre, à priori l'identifiant mais la source suffit.

**Comment by nriss** [comment]
En FHIR, il y a le system qui permet de dire dans quel système provient le code. Donc, je suis parti du principe que l'on allait identifier la source, de sorte à ce que le duo system / value soit suffisant pour identifier le concept de manière précise

Est-ce que ça te convient ?

**Comment by abreithoff** [comment]
C'est très clair, alors du coup, c'est la base SIRENE sirene.fr https://www.sirene.fr/sirene/public/accueil
et donc pour moi : 
System:

finess : [finess.local.esante.gouv.fr](http://finess.local.esante.gouv.fr/)
sirene: [siren.local.esante.gouv.fr](http://sirene.local.esante.gouv.fr/)
rpps : [rpss.local.esante.gouv.fr](http://rpps.local.esante.gouv.fr/)

**Comment by nriss** [comment]
Preview : https://ansforge.github.io/IG-fhir-annuaire/ig/main

Les system, dans le cas d'un identifiant national:
- IDNATPS : urn:oid:1.2.250.1.71.4.2.2
- SIREN/SIRET : http://sirene.fr (ou 1.3.2 ?)
- FINESS : http://finess.esante.gouv.fr
- ADELI/RPPS : https://annuaire.sante.fr

Si identifiant local, le system identifiant est comme tu l'as dit :
finess : [finess.local.esante.gouv.fr](http://finess.local.esante.gouv.fr/)
sirene: [siren.local.esante.gouv.fr](http://sirene.local.esante.gouv.fr/)
rpps : [rpss.local.esante.gouv.fr](http://rpps.local.esante.gouv.fr/)

**Comment by abreithoff** [comment]
OK pour moi, avec deux correctifs  : 
finess : [finess.local.esante.gouv.fr](http://finess.local.esante.gouv.fr/)
sirene: [sirene.local.esante.gouv.fr](http://sirene.local.esante.gouv.fr/)
rpps : [rpps.local.esante.gouv.fr](http://rpps.local.esante.gouv.fr/)
