### ISSUE TITLE
[NARRATIF] Eclaircir l'articulation NOS / FHIR 

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#67]
https://github.com/ansforge/IG-fhir-annuaire/blob/876867e8d70e40b3e86c2295ab30ac050ac5730a/input/pagecontent/index.md?plain=1#L22C1-L23C1

Préciser que le NOS est une description fonctionnelle des concepts, et que l'IG est une description technique de comment est exposé les ressources FHIR via l'API.

**Comment by mchaabaoui** [comment]
+mapping fhir/mos
