### ISSUE TITLE
AS Organization Profile - Cardinalité slice Extension

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#68]
# Description du problème
Le slice pour les extensions d'Organization a une cardinalité minimum à 1. 
![image](https://github.com/ansforge/IG-fhir-annuaire/assets/122790741/559b91ec-da5d-40c2-89d3-11fa6939a5c1)

Je ne comprends pas pourquoi car de ce que je vois toutes les extensions sont optionnelles, non ? 

# Fichier•s concerné•s
AS Organization Profile
AS Donnée Publique Organization Profile 
 AS Donnée Restreinte Organization Profile 

# Solution proposée
Cardinalité 0..*

**Comment by nriss** [comment]
Profil concerné : 
- https://github.com/ansforge/IG-fhir-annuaire/blob/main/input/fsh/profiles/AsOrganizationProfile.fsh
- https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-organization.html

Avec @mchaabaoui, nous n'avons pas trouvé d'où vient cette cardinalité minimale placée à 1. Pourrais-tu investiguer @paulineheurtebise ?
