### ISSUE TITLE
Changer le nom du repo en  IG-fhir-annuaire

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#7]
Egalement changer les données ici : https://github.com/ansforge/IG-fhir-annuaire-donnee-publique/blob/main/sushi-config.yaml
id = ans.fhir.fr.annuaire
canonical: http://interop.esante.gouv.fr/ig/fhir/annuaire
...

**Comment by mchaabaoui** [comment]
c'est fait
