### ISSUE TITLE
Création d'un menu déroulant pour l'accès aux profils ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#76]
proposition de Clotaire Delanchy

**Comment by mchaabaoui** [comment]
Discuté avec @nriss 
Pas très pratique car implique une gestion manuelle dudit  menu
A explorer la piste d'ajouter le menu au sein de l'IG publisher si nécessaire

**Comment by nriss** [comment]
P-e que l'on peut générer qqc avec ceci automatiquement : https://build.fhir.org/ig/FHIR/ig-guidance/sql.html

A creuser

**Comment by nriss** [comment]
Ayant avancé sur la génération automatique, je trouve que ça ne faciliterait pas la lecture étant donné qu'il y a beaucoup de profils.
Cependant, pour faciliter l'accès aux profils, nous avons :

- Généré des tableaux dans la page "Liste des profils"
- Généré un tableau contenant les profils génériques sur la page d'accueil
![image](https://github.com/ansforge/IG-fhir-annuaire/assets/48218773/82fadbb1-549f-4ee6-83ed-2c66d443552d)

Je clos l'issue, n'hésite pas à la rouvrir si besoin @cdelanchy
