### ISSUE TITLE
A quoi servent ces extensions ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#8]
https://github.com/ansforge/IG-fhir-annuaire-donnee-publique/blob/fd23a188c249c0443310c68b4657fa60b094f8ec/input/fsh/profiles/AsPractitionerProfile.fsh#LL22C72-L22C72

**Comment by mchaabaoui** [comment]
Remarque prise en compte

**Comment by mchaabaoui** [comment]
ces extensions ont été retirées.
