### ISSUE TITLE
Practitioner inactif

### ISSUE THREAD

**Issue by mchaabaoui** [ansforge/IG-fhir-annuaire#80]
https://participez.esante.gouv.fr/project/implementation-guide-annuaire/collect/deposer-une-contribution/proposals/practitioner-inactif

**Comment by mchaabaoui** [comment]
Pour rappel, le périmètre de l'API FHIR de l'annuaire santé en libre accès : 
Uniquement les données actives et publiques, PS actifs au sens autorisé à exercer et structures actives. 
Par conséquent, nous ne fournissons pas d'historique de ressources FHIR.

Néanmoins, la prochaine version de l'API (dite 1.26) proposera une nouvelle fonctionnalité très pratique visant à aider les consommateurs du delta à identifier les ressources supprimées entre deux synchronisations (en marquant la ressource supprimée comme inactive "active=false")

Par ailleurs, merci pour le usecase "comment être informé qu'une adresse MSSanté n'est plus valide" que nous allons étudier très attentivement.

**Comment by abreithoff** [comment]
Bonjour, 

il ne va pas être possible de rendre disponible en libre accès le motif de fin d'activité pour la simple et bonne raison que ce champs est renseigné par les autorités d'enregistrement au moment de la fermeture de la situation d'exercice du professionnel. Or, une situation d'exercice fermée n'est pas une donnée en libre accès. A partir du moment où cette situation d'exercice est fermée, il n'est plus possible de publier les informations la concernant.

**Comment by celinegach** [comment]
Bonjour,
Des données de date de fin et motif sont présents dans certains cas avant la fermeture, ce qui permet d'anticiper certaines situations, c'est la raison de ma demande.
En tout cas, c'est noté, je vous remercie pour votre réponse. 
Bonne journée à vous

**Comment by abreithoff** [comment]
Effectivement, il arrive parfois que l'autorité d'enregistrement indique à l'avance la fermeture "future" d'une situation d'exercice, Nous étudierons la mise à disposition de cette information en même temps que d'autres demandées par ailleurs. Cela nécessite une instruction juridique qui peut être longue, pour un cas somme toute assez rare. Nous allons donc tout de même fermer cet issus.
