### ISSUE TITLE
Associer valueSet à streetNameType (type de voie) ?

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#81]
# Description du problème
Dans le DSFT et sur le service actuel de l'Annuaire, le type de voie (streetNameType ) est un String avec Binding sur JDV_J103-TypeVoie-RASS (dérivé de la TRE_R35-TypeVoie)

Dans l'IG actuellement, il n'y a pas mention du binding vers le value Set. 
Est ce que c'est un choix et une évolution par rapport au service actuel ?  

# Fichier•s concerné•s
[AsAddressExtendedProfile](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-address-extended.html)
Extension [streetNameType](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-address-extended-definitions.html#Address.line.extension:streetNameType)

# Solution proposée

**Comment by nriss** [comment]
Discussion avec Mohammed: privilégier le type code avec un binding vers le JDV J103
