### ISSUE TITLE
Ajouter explication Missing data ?

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#82]
# Description du problème
Un des questions de la CNAM sur le DSFT est sur l'interprétation des valeurs vides. 
Actuellement, le service en production répond tous les attributs d'une ressource, que ces attributs contiennent des données ou pas. 

# Fichier•s concerné•s
/

# Solution proposée
Est ce qu'il serait intéressant d'ajouter une précision dans l'IG sur ce format de réponse et la présence de missing data ? 
Afin d'éviter toutes questions à l'avenir sur le fonctionnement du service et l'interprétation des données vides ("null" ou []) 

Lors de ma recherche pour la réponse à la CNAM et la position de FHIR sur ce sujet, j'étais tombé sur cet IG, dont il est peut - être possible de s'inspirer : https://build.fhir.org/ig/HL7/fhir-sdoh-clinicalcare/mustsupport_and_missing_data.html

**Comment by nriss** [comment]
Peut-être privilégier l'usage de l'extension [DataAbsentReason Extension](http://hl7.org/fhir/R4/extension-data-absent-reason.html) ?
