### ISSUE TITLE
Expliciter les attributs utilisés pour le Lieu de naissance du PS ? 

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#85]
# Description du problème
Ce point fait partie des questions posées par la CNAM. 

Le lieu de naissance du PS est véhiculé via une [Extension AS Practitioner Birth Place](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-ext-practitioner-birth-place.html). 

Cette extension est de type [AS Address Extended Datatype Profile](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-address-extended.html)

Dans l'IG (c'était aussi le cas dans le DSFT), il n'y a pas de précision concernant les attributs utilisés pour définir le lieu de naissance à partir de l'adresse. 

![image](https://github.com/ansforge/IG-fhir-annuaire/assets/122790741/fd562e50-57bc-4607-b887-514f4cb5f11e)

De ce que j'en comprends, le lieu de naissance peut utiliser 3 attributs pour être défini : 
- Address.text = Nom de la ville de naissance
- Address.extension.inseeCode = Si français code issu du JDV fr-insee-code Sinon non renseigné
- Address.extension.countryCode = Code issu JDV_J74-Pays-RASS Si français code 99000

# Fichier•s concerné•s
Profile [AS Practitioner Profile](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-practitioner.html)
[Extension AS Practitioner Birth Place](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-ext-practitioner-birth-place.html)
[AS Address Extended Datatype Profile](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-address-extended.html)

# Solution proposée

Pour plus de clarté, serait - il possible d'expliciter les attributs utilisés pour le lieu de naissance, au moins dans le narratif, ou autre si vous avez des idées ?

**Comment by nriss** [comment]
S'agit-il de modifications à faire au niveau d'InteropSanté ?
https://github.com/Interop-Sante/hl7.fhir.fr.core/blob/main/input/fsh/datatype-profiles/FRCoreAddressProfile.fsh

**Comment by paulineheurtebise** [comment]
Je ne suis pas certaine, j'ai l'impression qu'on est que sur du narratif ici. 
On profile pas l'adresse pour le birth place ou d'autres usages. Ici on a 1 type de donnée adresse que nous utilisons dans des usages différents, donc des attributs spécifiques seront utilisés à chaque fois mais on précise nul part lesquels. 
Est ce que ce n'est juste une problématique de narratif /mapping ?

**Comment by nriss** [comment]
L'objectif est d'indiquer quelles ressources sont exposées par l'annuaire, c'est bien ça ?

Si oui, on peut mettre des tags MS dans les attributs mappés, au niveau de AsPatient.extension[birthplace].valueAddress.[...] (au niveau de la ressource Patient et non du profil FrAddress)

**Comment by paulineheurtebise** [comment]
Effectivement c'est une bonne idée les tags. 
D'ailleurs je relisais la spec FHIR sur le Must Support, est ce que pour l'Annuaire il ne faut pas un endroit qui explique ce que veut dire le MS dans ce contexte ? ["When a profile does this, it SHALL also make clear exactly what kind of "support" is required."](https://fhir-ru.github.io/profiling.html#mustsupport)

**Comment by nriss** [comment]
Très bonne idée @paulineheurtebise !

**Comment by mchaabaoui** [comment]
Tag MS : https://github.com/ansforge/IG-fhir-annuaire/issues/101
