### ISSUE TITLE
Ajouter le code 99000 dans le JDV_J74-Pays-RASS

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#86]
# Description du problème
Le code pays est associé au JDV_J74-Pays-RASS. 
https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-address-extended.html

Je vois 2 éléments à revoir : 

1. Il manque le code 99000 "France" dans le JDV. 
2. Dans le narratif il est précisé que le code sur 3 caractères avec exemple "FRA", le problème c'est que dans le JDV le code est sur 5 caractères

![image](https://github.com/ansforge/IG-fhir-annuaire/assets/122790741/30fcdd7d-0c8a-47e5-a2c7-91bb7e6afd8c)

# Fichier•s concerné•s
[AS Address Extended Datatype Profile](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-address-extended.html)
[JDV_J74-Pays-RASS](https://mos.esante.gouv.fr/NOS/JDV_J74-Pays-RASS/JDV_J74-Pays-RASS.pdf)

# Solution proposée

1. Ajouter le code 99000 dans le JDV ? 
2. Modifier le narratif ou le JDV associé pour assurer une cohérence entre la description et le JDV associé ?

**Comment by paulineheurtebise** [comment]
Après investigation, le COG officiel de la France est 99100 (validé par data.gouv). Ce code est bien présent dans le JDV. 
Cependant dans le DSFT, c'est l'ancien COG 99000 qui est précisé. 
![image](https://github.com/ansforge/IG-fhir-annuaire/assets/122790741/c584c13f-75b2-4cb8-b647-a5616266aa91)
Est ce qu'il faut conservé le code 99000 dans le JDV le temps d'une bascule ?

**Comment by abreithoff** [comment]
C'est le code historique avec lequel échange le SI RPPS  et les autorités d'enregistrement. Il n'y a pas de chantier de bascule du code 99000 vers 99100 actuellement côté RPPS, à lancer si nécessaire avec l'équipe concernée.

**Comment by nriss** [comment]
Peut-on clore cette issue @paulineheurtebise ?

**Comment by paulineheurtebise** [comment]
Oui je clos.
