### ISSUE TITLE
Ces slices étant déjà définies dans le profil parent : est-il réellement nécessaire de mettre ces contraintes ? Elles ne sont pas déjà dans les profils français ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#9]
https://github.com/ansforge/IG-fhir-annuaire-donnee-publique/blob/fd23a188c249c0443310c68b4657fa60b094f8ec/input/fsh/profiles/AsPractitionerProfile.fsh#L94

**Comment by mchaabaoui** [comment]
Remarque prise en compte

**Comment by mchaabaoui** [comment]
ces contraintes inutiles ont été supprimées.

**Comment by nriss** [comment]
Les contraintes sur ces slices y sont encore : https://github.com/ansforge/IG-fhir-annuaire/blob/fd23a188c249c0443310c68b4657fa60b094f8ec/input/fsh/profiles/AsPractitionerProfile.fsh#L94
