### ISSUE TITLE
Slice à faire sur Practitioner.name ?

### ISSUE THREAD

**Issue by paulineheurtebise** [ansforge/IG-fhir-annuaire#91]
# Description du problème
Pourquoi est ce que le name n'est pas slicé selon la valeur de use ? 
Comme il est précisé dans le narratif qu'il y en a 2 et qu'un discriminateur existe, est ce qu'il y a une raison pour ne pas slicer ? 

# Fichier•s concerné•s
[Profil Practitioner](https://interop.esante.gouv.fr/ig/fhir/annuaire/StructureDefinition-as-practitioner.html)
Attribut name 

# Solution proposée
Slice de name avec disciminateur la valeur de name.use

**Comment by mchaabaoui** [comment]
je suis d'accord

**Comment by nriss** [comment]
Je ne sais pas trop si ça apporte qqc parce que tout est déjà présent, mais si ça vous semble plus clair, aucun soucis pour moi :)

**Comment by nriss** [comment]
Discuté avec @zilliw, pas nécessaire
