### ISSUE TITLE
La boite mss est une donnée pulique et ne devrait pas être en cardinalité 0..0

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#93]
https://github.com/ansforge/IG-fhir-annuaire/blob/872e4d61ceaef2134bfc427c9ebf4d5b7a207d1d/input/fsh/profiles-dp/AsDpOrganizationProfile.fsh#L13

Discuté avec @abreithoff lors du point MES le 19 octobre 2023

**Comment by mchaabaoui** [comment]
Effectivement, ce sera corrigé.
