### ISSUE TITLE
Faut-il ajouter une extension code commune (cog) au profil du datatype FrAddress ?

### ISSUE THREAD

**Issue by nriss** [ansforge/IG-fhir-annuaire#96]
Besoin du ROR pour uniformisation @jcserafini @sdemeyANS 

@paulineheurtebise @mchaabaoui qu'en pensez-vous ?

cf https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/issues/155

**Comment by paulineheurtebise** [comment]
De ma compréhension, c'est pas nécessaire, aujourd'hui l'Annuaire s'appuie sur le valueSet d'Interop qui repose sur la TRE_R13-Communes. Je pense qu'il est préférable de conserver l'utilisation du VS Interop, déjà présent dans FrAddress. 
Côté ROR, j'ai répondu dans le même sens, je pense pas qu'il soit nécessaire d'utiliser le JDV NOS.
